#!/usr/bin/env python3
"""Generate the README's plugin list from the marketplace manifest.

The list used to be hand-written, one section per plugin, and it drifted by
construction: an automated bump rewrites `.claude-plugin/marketplace.json`
and nothing else, so a plugin could be served by the catalog and absent from
the README with nothing to notice.  `scholar-mcp` was, for months.

So the list is generated from the manifest, into a marked region of an
otherwise hand-written README.  The `GENERATED-` marker prefix follows the
convention the server template uses for the same job: it is deliberately
distinct from hand-owned sentinels, and means the region is machine-owned
and rewritten on every run — nothing between the markers should ever be
edited by hand.

Versions are deliberately NOT rendered.  Including them would make every
release rewrite this file, putting concurrent sibling releases on the same
lines; the manifest and `/plugin` are where versions live.  Leaving them out
means the README changes only when the plugin set or its prose changes.

Run with no arguments to rewrite the region.  Pass `--check` to verify it is
current without writing — that is what CI runs.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / ".claude-plugin" / "marketplace.json"
README = REPO_ROOT / "README.md"

REGION_ID = "PLUGIN-LIST"
START_MARKER = (
    f"<!-- GENERATED-{REGION_ID}-START — generated by scripts/gen_readme.py; "
    "do not edit -->"
)
END_MARKER = f"<!-- GENERATED-{REGION_ID}-END -->"


def _source_link(entry: dict[str, Any]) -> str | None:
    """A "where does this come from" line, by source type."""
    source = entry.get("source")
    if isinstance(source, str):
        path = source.lstrip("./")
        return f"- **Source:** [`{path}`]({path}) — in this repository"
    if not isinstance(source, dict):
        return None
    kind = source.get("source")
    if kind == "git-subdir" or kind == "url":
        url = str(source.get("url", "")).removesuffix(".git")
        if not url:
            return None
        label = url.split("github.com/", 1)[-1] if "github.com/" in url else url
        return f"- **Source:** [{label}]({url})"
    if kind == "github":
        repo = str(source.get("repo", ""))
        if not repo:
            return None
        return f"- **Source:** [{repo}](https://github.com/{repo})"
    return None


def render_region() -> str:
    """The generated body, in manifest order."""
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    blocks: list[str] = []
    for entry in data.get("plugins", []):
        if not isinstance(entry, dict) or not entry.get("name"):
            continue
        lines = [f"### {entry['name']}", ""]
        description = " ".join(str(entry.get("description", "")).split())
        if description:
            lines += [description, ""]
        source_link = _source_link(entry)
        if source_link:
            lines.append(source_link)
        homepage = entry.get("homepage")
        # Only for remote entries: an in-repo plugin's homepage is its own
        # directory, which the source link already points at.
        if homepage and isinstance(entry.get("source"), dict):
            lines.append(f"- **Homepage:** <{homepage}>")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def splice(text: str, body: str) -> str:
    """Replace the marked region, leaving the rest of the file untouched.

    Fails loudly rather than guessing: a missing, duplicated, or inverted
    marker pair means the README no longer says where the generated content
    belongs, and silently appending it somewhere would be worse than
    stopping.
    """
    for marker, name in ((START_MARKER, "START"), (END_MARKER, "END")):
        count = text.count(marker)
        if count == 0:
            raise SystemExit(
                f"ERROR: README.md has no GENERATED-{REGION_ID}-{name} marker — "
                "this generator only rewrites the marked region, never the "
                "surrounding file."
            )
        if count > 1:
            raise SystemExit(
                f"ERROR: README.md has {count} GENERATED-{REGION_ID}-{name} "
                "markers; exactly one is required."
            )
    start = text.index(START_MARKER)
    end = text.index(END_MARKER)
    if end < start:
        raise SystemExit(
            f"ERROR: README.md's GENERATED-{REGION_ID}-END marker precedes its "
            "START marker."
        )
    newline = text.find("\n", start)
    before = text[: newline + 1 if newline != -1 else len(text)]
    after = text[end:]
    return f"{before}\n{body}\n\n{after}" if body else f"{before}{after}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the generated region is up to date without writing it.",
    )
    args = parser.parse_args()

    if not MANIFEST.is_file():
        print(f"ERROR: {MANIFEST} is missing.", file=sys.stderr)
        return 1
    if not README.is_file():
        print(f"ERROR: {README} is missing.", file=sys.stderr)
        return 1

    current = README.read_text(encoding="utf-8")
    rendered = splice(current, render_region())

    if rendered == current:
        if not args.check:
            print("README.md plugin list already up to date.")
        return 0

    if args.check:
        print(
            "STALE: README.md's generated plugin list is out of date — run: "
            "python3 scripts/gen_readme.py",
            file=sys.stderr,
        )
        return 1

    README.write_text(rendered, encoding="utf-8")
    print("Wrote README.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
